name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: amd64
            name: photon-macos-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            name: photon-macos-arm64
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            name: photon-linux-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            name: photon-windows-amd64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: go build -ldflags="-s -w" -o ${{ matrix.name }} ./cmd/photon
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
          generate_release_notes: true
